version: '2'
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./containers/php-fpm
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - db
    nginx:
        build: ./containers/nginx
        ports:
            - "81:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
#    elk:
#        image: willdurand/elk
#        ports:
#            - "81:80"
#        volumes:
#            - ./containers/elk/logstash:/etc/logstash
#            - ./containers/elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
