route_index:
    path: /
    defaults: { _controller: 'App\Controller\StaticController::homepage' }

route_dashboard:
    path: /tableau-de-bord
    defaults: { _controller: 'App\Controller\DashboardController::dashboard' }

### Incinérateur
route_history:
    path: /historique/{incinerateurId}
    defaults: { _controller: 'App\Controller\IncinerateurController::historique' }

route_cr_declaration:
    path: /historique/declaration-mesures-continues/{declarationId}
    defaults: { _controller: 'App\Controller\DeclarationMesuresContinuesController::compteRendu' }

route_cr_declaration_dioxine:
    path: /historique/declaration-dioxine/{declarationId}
    defaults: { _controller: 'App\Controller\IncinerateurController::crDioxine' }

### Owner
route_dashboard_owner:
    path: /tableau-de-bord-exploitant
    defaults: { _controller: 'App\Controller\OwnerController::dashboard' }

route_declaration:
    path: /declarer
    defaults: { _controller: 'App\Controller\OwnerController::declarationChoice' }

route_declaration_dioxines:
    path: /declarer-dioxines
    defaults: { _controller: 'App\Controller\OwnerController::declarationDioxines' }

route_declaration_mesures_continues:
    path: /declarer-mesures-continues
    defaults: { _controller: 'App\Controller\DeclarationMesuresContinuesController::declare' }

route_review_declaration_mesures_continues:
    path: /verification-declaration-mesures-continues/{declarationId}
    defaults: { _controller: 'App\Controller\DeclarationMesuresContinuesController::review' }

route_edit_declaration_mesures_continues:
    path: /modification-declaration-mesures-continues/{declarationId}
    defaults: { _controller: 'App\Controller\DeclarationMesuresContinuesController::modify' }

route_validate_declaration_mesures_continues:
    path: /fin-declaration-mesures-continues/{declarationId}
    defaults: { _controller: 'App\Controller\DeclarationMesuresContinuesController::validate' }

route_download_asset:
    path: /telecharger-ressource
    defaults: { _controller: 'App\Controller\OwnerController::downloadAsset' }

### Inspecteur
route_liste_incinerateurs:
    path: /liste-incinerateurs
    defaults: { _controller: 'App\Controller\InspecteurController::liste_incinerateurs' }

route_dashboard_incinerateur:
    path: /tableau-de-bord-incinerateur/{incinerateurId}
    defaults: { _controller: 'App\Controller\DashboardController::dashboard_incinerateur' }

route_dashboard_incinerateur_ligne:
    path: /tableau-de-bord-incinerateur/{incinerateurId}/ligne/{ligneId}
    defaults: { _controller: 'App\Controller\DashboardController::dashboard_ligne' }


### Login
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"