route_index:
    path: /
    defaults: { _controller: 'App\Controller\StaticController::homepage' }

route_dashboard:
    path: /tableau-de-bord
    defaults: { _controller: 'App\Controller\UserController::dashboard' }

### Incinérateur
route_history:
    path: /historique/{incinerateurId}
    defaults: { _controller: 'App\Controller\IncinerateurController::historique' }

route_cr_declaration:
    path: /historique/declaration-mesures-continues/{declarationId}
    defaults: { _controller: 'App\Controller\IncinerateurController::cr' }

route_cr_declaration_dioxine:
    path: /historique/declaration-dioxine/{declarationId}
    defaults: { _controller: 'App\Controller\IncinerateurController::crDioxine' }

#route_cr_sample:
#    path: /compte-rendu
#    defaults: { _controller: 'App\Controller\IncinerateurController::crSample' }

### Owner
route_dashboard_owner:
    path: /tableau-de-bord-exploitant
    defaults: { _controller: 'App\Controller\OwnerController::dashboard' }

route_declaration:
    path: /declarer
    defaults: { _controller: 'App\Controller\OwnerController::declaration' }

route_declaration_dioxines:
    path: /declarer-dioxines
    defaults: { _controller: 'App\Controller\OwnerController::declarationDioxines' }

route_declaration_mesures_continues:
    path: /declarer-mesures-continues
    defaults: { _controller: 'App\Controller\OwnerController::declarationMesuresContinues' }


route_download_asset:
    path: /telecharger-ressource
    defaults: { _controller: 'App\Controller\OwnerController::downloadAsset' }

### Inspecteur

route_dashboard_inspecteur:
    path: /tableau-de-bord-inspecteur
    defaults: { _controller: 'App\Controller\InspecteurController::dashboard_inspecteur' }

route_liste_incinerateurs:
    path: /liste-incinerateurs
    defaults: { _controller: 'App\Controller\InspecteurController::liste_incinerateurs' }

route_dashboard_incinerateur:
    path: /tableau-de-bord-incinerateur/{incinerateurId}
    defaults: { _controller: 'App\Controller\InspecteurController::dashboard_incinerateur' }

### Login
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"