route_index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

route_dashboard:
    path: /tableau-de-bord
    defaults: { _controller: 'App\Controller\UserController::dashboard' }

route_declaration:
    path: /declaration
    defaults: { _controller: 'App\Controller\UserController::declaration' }

route_cr:
    path: /compte-rendu
    defaults: { _controller: 'App\Controller\UserController::cr' }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"