route_index:
    path: /
    defaults: { _controller: 'App\Controller\StaticController::homepage' }

route_dashboard:
    path: /tableau-de-bord
    defaults: { _controller: 'App\Controller\UserController::dashboard' }

route_declaration:
    path: /declaration
    defaults: { _controller: 'App\Controller\OwnerController::declaration' }

route_download_template:
    path: /telecharger-modele
    defaults: { _controller: 'App\Controller\OwnerController::downloadDeclarationTemplate' }

route_history:
    path: /historique/{incinerateurId}
    defaults: { _controller: 'App\Controller\UserController::historique' }

route_cr:
    path: /compte-rendu
    defaults: { _controller: 'App\Controller\UserController::cr' }

route_liste_incinerateurs:
    path: /liste-incinerateurs
    defaults: { _controller: 'App\Controller\UserController::liste_incinerateurs' }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"