fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "noreply@keiruaprod.fr"
        sender_name: "No Reply"
    registration:
        confirmation:
            enabled: false
    resetting:
        email:
            from_email:
                address:        resetting@example.com
                sender_name:    Demo Resetting

#services:
#    fos_user.command.activate_user:
#        class: FOS\UserBundle\Command\ActivateUserCommand
#        tags:
#            - { name: console.command }
#
#    fos_user.command.change_password:
#        class: FOS\UserBundle\Command\ChangePasswordCommand
#        tags:
#            - { name: console.command }
#
#    fos_user.command.create_user:
#        class: FOS\UserBundle\Command\CreateUserCommand
#        tags:
#            - { name: console.command }
#
#    fos_user.command.deactivate_user:
#        class: FOS\UserBundle\Command\DeactivateUserCommand
#        tags:
#            - { name: console.command }
#
#    fos_user.command.demote_user:
#        class: FOS\UserBundle\Command\DemoteUserCommand
#        tags:
#            - { name: console.command }
#
#    fos_user.command.promote_user:
#        class: FOS\UserBundle\Command\PromoteUserCommand
#        tags:
#            - { name: console.command }#