vich_uploader:
    db_driver: orm

    mappings:
        declaration_incinerateur:
            uri_prefix: '/declarations/incinerateur'
            upload_destination: '%kernel.project_dir%/public/declarations/incinerateur'
