vich_uploader:
    db_driver: orm

    mappings:
        declaration_incinerateur:
            uri_prefix: '/build/declarations'
            upload_destination: '%kernel.project_dir%/public/build/declarations'
            namer: vich_uploader.namer_origname