vich_uploader:
    db_driver: orm

    mappings:
        declaration_incinerateur:
            uri_prefix: '/declaration-incinerateur'
            upload_destination: '%kernel.project_dir%/public/declarations'
            namer: vich_uploader.namer_origname